services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./EtiquetaCertaCaseDB.sql:/docker-entrypoint-initdb.d/EtiquetaCertaCaseDB.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etiquetacerta.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
